# "service" is the name of this project. This will also be added to your AWS resource names.
service: accounts-service

provider:
  name: aws
  runtime: nodejs18.x

package:
  individually: true
  exclude:
    - node_modules/**

build:
  esbuild:
    packages: external

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
